### ISSUE TITLE
It doesnt appear in roblox

### ISSUE THREAD

**Issue by b3eee** [Raihann22/Roblox-Player-Server-Searcher#11]
Hi! I tried installing this but for some reason it doesnt appear in the page of a game in roblox!
![image](https://github.com/user-attachments/assets/a4915ad1-37ba-4e32-83d6-04877ef0c1bc)

as u can see it looks the same! what do i do?

**Comment by Raihann22** [comment]
Could you please let me know what other Roblox extensions you use?

**Comment by b3eee** [comment]
yeyeyey! i use this oens 
![image](https://github.com/user-attachments/assets/707740bf-014a-4528-a1a8-11ab1d6f42e0)

**Comment by b3eee** [comment]
WAIT, I FOUND IT!!

**Comment by Raihann22** [comment]
It looks like you might have already found or fixed the problem, but if the issue still occurs, you can download this file [(page-games.js)](https://github.com/Raihann22/Roblox-Player-Server-Searcher/blob/main/js/page-games.js) and replace the old file in the `js/page-games.js` folder. This should solve the issue. 

Let me know if you encounter any further problems.
