### ISSUE TITLE
Forever loading

### ISSUE THREAD

**Issue by getram3** [Raihann22/Roblox-Player-Server-Searcher#21]
Enter username, click search. No errors popup but nothing happens and I get the blue spinning wheel cursor. It stays like this unless I reload the page and if I repeat the search it just happens all over again.

**Comment by Raihann22** [comment]
What version do you use?

**Comment by getram3** [comment]
2.2.1, latest version

**Comment by Raihann22** [comment]
Try this version **[v3.0.0-beta](https://github.com/Raihann22/Roblox-Player-Server-Searcher/releases/tag/v3.0.0-beta1)**

**Comment by getram3** [comment]
Works on some games. I can't get it to work on Jailbreak, it still does the forever loading thing.

**Comment by getram3** [comment]
Nvm, it just takes awhile, the loading bar stops, gives the blue spinny wheel, then the page will flash and load roblox client
