### ISSUE TITLE
The progress bar isn't updating accurately.

### ISSUE THREAD

**Issue by Raihann22** [Raihann22/Roblox-Player-Server-Searcher#4]
**File: [Roblox-Player-Server-Searcher/js/searcher.js](https://github.com/Raihann22/Roblox-Player-Server-Searcher/tree/main/js/searcher.js)
From line 268.**

The progress bar isn't updating accurately with the new changes. It jumps from 0% to 50% to 100% when processing 4000 tokens because it updates every 2000 tokens (maxParallelRequests * 100).
```js
        for (let currentIndex = 0;
            currentIndex < allTokens.length;
            currentIndex += maxParallelRequests * 100) {
            /*
            slice = [allTokens[x], ...98x , allTokens[ (x+99) | (allTokens.length-1) ] ]
            slices = [ slice, ...(maxParrallelRequests-2)x, slice ];
            */
            const slices = [];
            for (let requestIndex = 0; requestIndex < maxParallelRequests; requestIndex++) {
                const start = currentIndex + requestIndex * 100;
                if (start >= allTokens.length) break;
                slices.push(allTokens.slice(start, Math.min(start + 100, allTokens.length)));
            }
            const userFound = await processSlices(slices);
            if (userFound) return foundUser;
            PROGRESS_BAR.style.width = `${Math.ceil(currentIndex / onePercent)}%`;
        }
```

How To Fix?
Maybe move it to Array map() Method in [line 265](https://github.com/Raihann22/Roblox-Player-Server-Searcher/blob/ca9036e147888e1da2b60b0bf6a6b8cde6076f7f/js/searcher.js#L265)

**Comment by PirAhmedShah** [comment]
Fixed the issue in new PR by updating progress bar inside checkUserBatch().
