### ISSUE TITLE
Im stuck

### ISSUE THREAD

**Issue by AzuraDoes** [Raihann22/Roblox-Player-Server-Searcher#8]
I need to refresh it so i will be back to the regular roblox tab I dont think its working

<img width="638" alt="image" src="https://github.com/user-attachments/assets/bdc1584d-ce19-4bd6-9a66-b40f235b3ea1">

I cant scroll down and stuff the only way to get out of it is to refresh the page

Edit: Never mind. I increased zoom size and it worked lol

**Comment by Raihann22** [comment]
The EULA HTML is currently set to a fixed width and height, which makes it difficult to view on smaller monitors. I'll make it responsive in the next version to fix this issue.

**Comment by Raihann22** [comment]
Fixed [#f435e6b ](https://github.com/Raihann22/Roblox-Player-Server-Searcher/commit/f435e6b2bc987a82b45eb902006a443b41b5523e)
